### ISSUE TITLE
coord.py key value 노출

### ISSUE THREAD

**Issue by LBR56** [SNOOthiking/enterprise#1]
안녕하세요...

워크넷 API 키가 필요해서 열심히 돌아다니고 있는 개발자 입니다...

여기에 API 키가 노출되어 있더라구요...

config.py 라는 파일을 만들어서 import 하게 바꾸시는게 좋을 것 같습니다.

.gitignore를 검색하시면 어떻게 config 파일을 숨길 수 있는지 나올 것입니다!

**Comment by SNOOthiking** [comment]
고맙습니다.  파일 관리를 다 끝내고 하는 안좋은 습관이 있어서 앞으로 주의해야겠습니다. 
파일 숨기는 법 알려주셔서 감사합니다. 
키는 조만간 api 연결 해제할 예정입니다. 그 때까지는 뭐 이미 노출된거 워크넷정책에 위배되지않는 선에서는 사용하셔도 ..

**Comment by LBR56** [comment]
압도적으로 감사합니닷 ㅠㅜㅠㅜ

**Comment by SNOOthiking** [comment]
p{margin-top:0;margin-bottom:0}
    


    앗 감사합니다. 다 지웠다고 생각했는데 ㅎㄷ..좋은 하루 되시기 바랍니다~
--------- 원본 메일 ---------

    
        보낸사람: LBR ***@***.***>
        받는사람: SNOOthiking/enterprise ***@***.***>
        
            참조: Subscribed ***@***.***>
        
        날짜: 22.07.19 11:10 GMT +0900
        제목: [SNOOthiking/enterprise] coord.py key value 노출 (Issue #1)
        
        
    
    
        

안녕하세요...

워크넷 API 키가 필요해서 열심히 돌아다니고 있는 개발자 입니다...

여기에 API 키가 노출되어 있더라구요...

config.py 라는 파일을 만들어서 import 하게 바꾸시는게 좋을 것 같습니다.

.gitignore를 검색하시면 어떻게 config 파일을 숨길 수 있는지 나올 것입니다!



—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

�
